development:
  test_string: "it's test string, check it"

  #Общие настройки
  lottery_title: "девол_Стандартный заголовок из конфига"

  #Работа со steamcommunity
  steam_rsa_url: "https://steamcommunity.com/login/getrsakey/"
  steam_auth_url: "https://steamcommunity.com/login/dologin/"
  steam_trade_url: "https://steamcommunity.com/tradeoffer/new/send"

  #Работа с openid
  steam_openid: "http://steamcommunity.com/openid"

  #Ключи DEV API
  api_key: "40203AB5100825DF97F990FCE10E7916"

  #Сколько минут ждать подтверждения
  tradeoffer_timeout: 1

  #Секретный ключ для шифрования assetid и marker_hash_name
  secret_key: "i_want_one_million_dollars"

production:
  test_string: "it's test string, check it"

  #Общие настройки
  lottery_title: "прод_Стандартный заголовок из конфига"

  #Работа со steamcommunity
  steam_rsa_url: "https://steamcommunity.com/login/getrsakey/"
  steam_auth_url: "https://steamcommunity.com/login/dologin/"
  steam_trade_url: "https://steamcommunity.com/tradeoffer/new/send"

  #Работа с openid
  steam_openid: "http://steamcommunity.com/openid"

  #Ключи DEV API
  api_key: "40203AB5100825DF97F990FCE10E7916"

  #Сколько минут ждать подтверждения
  tradeoffer_timeout: 5

  #Секретный ключ для шифрования assetid и marker_hash_name
  secret_key: "i_want_one_million_dollars"
test: